name: Build
on:
  push:
    branches:
      - master
      - develop
      - build

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v1

      - name: Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: npm install and npm run build
        run: |
          npm ci
          npm run-script build-prod
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}